version: '3'
services:
    nginx-unit:
        image: nginx/unit
        ports:
            - "88:8080"
        volumes:
            - ./demo-app:/demo-app
            - ./config.json:/demo-app/config.json