version: '3'
services:
    nginx-unit:
        image: unit:latest
        ports:
            - "88:80"
        volumes:
            - ./demo-app:/demo-app
            - ./config.json:/demo-app/config.json #curl -X PUT --data-binary @/demo-app/config.json --unix-socket unix:/var/run/control.unit.sock http://localhost/config


